Bk refactor doc site
filetrust/glasswall-sdk-site pull request #31
Opened 2021-01-21 17:34 UTC by gwBanzi

2021-01-22 08:48 UTC, mobrien-gw commented on docusaurus.config.js
> +      indexName: 'd0c_Site',
Is the zero in 'd0c' deliberate?

2021-01-22 08:52 UTC, mobrien-gw requested changes
typo in **docs/7-tools/7_4-dvl/dvlovervoew.jpg** . Should be **docs/7-tools/7_4-dvl/dvloverview.jpg**

2021-01-22 08:56 UTC, mobrien-gw commented on config.json
> +  }
Most parsers seem to like a newline on the last line, not an end-of-file marker. I usually edit and press the Carriage Return key on the last line.

2021-01-22 09:01 UTC, mobrien-gw commented on docs/2-glasswall_core/2_1-glasswall_rebuild/media/desktop.ini
> +[LocalizedFileNames]
These were generated by the Office Word Binary extension _Writage_ .

2021-01-22 09:02 UTC, mobrien-gw commented on docs/2-glasswall_core/2_2-glasswall_editor/2_2_8-core2_design_plan.md
> +title: 2.2.8 Core2 Design Plan
I must admit, I prefer "Core 2" rather than "Core2" but it's not something worth changing; however, we do need to be consistent.

2021-01-22 09:15 UTC, mobrien-gw requested changes

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_2-glasswall_editor/2_2_8-core2_design_plan.md
> +# Camera Pool
Numbered sections are useful to refer to, and the number of hashes is always one more than the number of dot-separated integers. There should be no Headers at level 1 (one hash) except for the main document header (if that). So we should have
## 1. Camera Pool
## 2. Export - Import
### 2.1 Version 2 Package
#### 2.1.1 Interface Object
#### 2.1.2 Import - Export Procedure

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_2-glasswall_editor/2_2_8-core2_design_plan.md
> +# Export – Import
Standardise on this. Here it is "Export - Import" and on line 39 it's "Export / Import".
I prefer a forward slash and no spaces around them, "Export/Import".

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_5-common/2_5_1-bddl.md
> +Glasswall has developed a tool called [Bin Directory Reader](../../7-tools/7_9-testing/7_9_1-BinDirectoryReader.md) using the Miraplacid Binary DOM SDK. The tool iterates over a directory of files, p
Docusaurus will not recognise the name if you specify the '.md' extension. The '.md' extension should not be used in links.

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_5-common/2_5_2-dvl.md
> +on DVL can be found in the [DVL Guide](../../3-guides/3_4-DVLGuide.md).
I'm surprised this works with the '.md' extension.

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_5-common/2_5_2-dvl.md
> +on the DVL Checker can be found in the [DVL Checker](../../7-tools/7_4-dvl/7_4_1-DVLChecker.md) page.
Remove '.md'.

2021-01-22 09:15 UTC, mobrien-gw commented on docs/2-glasswall_core/2_5-common/2_5_3-GlasswallCodeGenerators.md
> +- [Glasswall Developed Tools](../../7-tools/7_5-developer_tools/7_5_2-glasswall_developed_tools.md)
Remove '.md'.

2021-01-22 09:15 UTC, mobrien-gw commented on docs/5-development/5_1-development_process/5_1_1-new_camera_checklist.md
> +Test your BDD using [Bin Directory Reader](../../7-tools/7_9-testing/7_9_1-BinDirectoryReader.md) on large number of sample files.
Remove '.md'.

2021-01-22 15:52 UTC, gwBanzi commented on docs/2-glasswall_core/2_1-glasswall_rebuild/media/desktop.ini
> +[LocalizedFileNames]
Strange thing with this file, I haven't noticed it till now but I cant find it in my own folder structure.

2021-01-22 15:56 UTC, gwBanzi commented on docs/2-glasswall_core/2_2-glasswall_editor/2_2_8-core2_design_plan.md
> +title: 2.2.8 Core2 Design Plan
for uniformity going forward, I've changed it anyway so when new file come in they can stock to "core 2"

2021-01-25 15:40 UTC, mobrien-gw approved these changes

2021-01-26 12:29 UTC, merged